# Generated by Django 2.2.13 on 2020-08-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200809_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeassign',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
